-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Nov 22, 2022 at 09:44 AM
-- Server version: 5.7.33
-- PHP Version: 7.4.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shopper-ringier-sa`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `category_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_slug` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `order` int(11) NOT NULL,
  `visible` int(11) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `category_name`, `category_slug`, `order`, `visible`, `created_at`, `updated_at`) VALUES
(1, 'Furniture', 'furniture', 1, 1, '2022-11-22 04:29:17', '2022-11-22 04:29:17'),
(2, 'Electronics', 'electronics', 2, 1, '2022-11-22 04:29:17', '2022-11-22 04:29:17'),
(3, 'Cars', 'cars', 3, 1, '2022-11-22 04:29:17', '2022-11-22 04:29:17'),
(4, 'Property', 'property', 4, 1, '2022-11-22 04:29:17', '2022-11-22 04:29:17');

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(7, '2014_10_12_000000_create_users_table', 1),
(8, '2014_10_12_100000_create_password_resets_table', 1),
(9, '2019_08_19_000000_create_failed_jobs_table', 1),
(10, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(11, '2022_11_17_183714_create_products_table', 1),
(12, '2022_11_17_183836_create_categories_table', 1);

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `date_online` date NOT NULL,
  `date_offline` date NOT NULL,
  `price` decimal(8,2) NOT NULL,
  `currency` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mobile` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_id` bigint(20) NOT NULL,
  `image` text COLLATE utf8mb4_unicode_ci,
  `order` int(11) NOT NULL DEFAULT '1',
  `visible` int(11) NOT NULL DEFAULT '1',
  `created_by` bigint(20) NOT NULL,
  `updated_by` bigint(20) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `title`, `slug`, `description`, `date_online`, `date_offline`, `price`, `currency`, `mobile`, `email`, `category_id`, `image`, `order`, `visible`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES
(1, 'Prof. Gust Lindgren III', 'quos-qui-voluptatem-laboriosam-quam-consequatur-repellendus-sequi', 'Iste dolorem amet beatae quibusdam. Reprehenderit vel itaque ab. Aliquam magni provident fugit consectetur odit rerum itaque. Ipsam in quas dolorum sequi et quod quibusdam. Blanditiis voluptates doloribus ex in. Commodi illum et dolores. Incidunt et ducimus impedit eveniet. Aliquid laudantium magnam omnis et ratione molestias dolorem iste. Quisquam modi non id nobis consequatur. In non est ut dignissimos doloribus atque magnam. Necessitatibus aliquam non est similique veniam totam. Maiores ea consequatur molestiae rerum alias corrupti voluptas. Debitis iusto cum qui nostrum. Fugiat eaque reiciendis mollitia quia libero sed.', '2023-09-22', '2023-09-22', '4310.00', 'KES', '(757) 674-0274', 'reilly.keven@bayer.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(2, 'June Gutmann', 'odio-reprehenderit-harum-beatae-laudantium-saepe-sint-impedit-impedit', 'Quas non dolorem voluptatibus aspernatur facere rerum. Magni facere excepturi est temporibus quibusdam. Esse nemo earum aspernatur rerum optio. Omnis eveniet et quis vel. Saepe ipsa animi aliquid et. Ducimus esse nostrum sunt eum et nisi. Quia nostrum commodi in aliquid ut aut. Beatae illum vero soluta corrupti quo.', '2023-06-22', '2023-06-22', '950.00', 'KES', '+1-931-540-3498', 'spinka.earl@schaefer.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(3, 'Aiyana Quigley', 'tempora-odit-quasi-a-odio-et-ut-minus', 'Repudiandae optio cupiditate adipisci qui reiciendis officia. Eaque reiciendis quia sint quae. Facere eveniet amet eligendi quia esse tenetur pariatur. Animi velit ad non animi rem vero eaque. Facere ipsum non numquam dignissimos qui. Aut reiciendis distinctio cum enim soluta veniam accusantium. Laboriosam quod accusantium doloremque veniam voluptates voluptate. Quo voluptatibus nobis consequatur quam voluptas ut. Qui nihil suscipit ut quia. Corrupti perferendis repellat eaque incidunt ipsum est in. Ea non dolorum porro quis. Molestiae alias omnis odit vel. Et aut voluptas inventore omnis sed et ab. Iure qui rerum consequatur assumenda enim. Sint sed ut recusandae velit est doloribus.', '2023-01-22', '2023-01-22', '3138.00', 'KES', '951-772-9751', 'jschaefer@nikolaus.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(4, 'Devin Schmitt', 'ullam-laboriosam-voluptas-doloribus-ratione-vel-qui', 'Necessitatibus officiis laboriosam magni quis. Ut beatae veniam consequatur sequi rem dolorum ut facere. Quasi cum rerum modi veritatis vel. In laborum eius ipsum maiores et. Et earum consequatur aut corporis est et. Asperiores fugit dolor inventore adipisci. Eum consequatur non voluptatem ducimus qui excepturi. Pariatur perspiciatis in aut quasi.', '2023-01-22', '2023-01-22', '7298.00', 'KES', '(570) 751-7853', 'hbarton@hotmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(5, 'Prof. Blaze Kutch DDS', 'ex-voluptas-rerum-quo-sunt-quasi-repellendus-assumenda', 'Alias hic occaecati totam perferendis quia et nisi. Minus nobis et autem libero et sit provident dolores. Et repellendus sint est dolorem. Autem sint dolores tempore necessitatibus voluptate minima iure ut. Rem suscipit nesciunt eius quisquam sit maxime consequatur fuga. Minima et nihil hic omnis. Placeat voluptatibus nihil ea qui debitis non dolores sunt. Velit rem sunt aperiam et sapiente sint. Facere et consectetur eos exercitationem. Explicabo accusamus facere qui. Non doloribus illo officia ipsum provident ad sed. Sint et accusamus laborum eos rem tenetur. Quia repellat quidem deserunt laudantium ut unde. Tenetur ab debitis assumenda blanditiis.', '2023-05-22', '2023-05-22', '6706.00', 'KES', '(850) 584-1470', 'zulauf.kaleigh@gmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(6, 'Rosalind Zieme', 'magnam-laudantium-cumque-mollitia-consequatur-quae-eveniet', 'Unde aspernatur voluptatum et alias. Deleniti eaque reiciendis et ratione reprehenderit voluptas. Ratione aut aut aut dolores non sed. Veritatis consequatur ab nihil repellendus culpa alias. Quo dolorum illum ut consequatur. Quia aperiam quod consequatur ipsa quam consequuntur dicta aspernatur. Praesentium sunt sapiente eum voluptates. Soluta delectus velit a. Magni consectetur modi labore assumenda sequi consequatur sint fugiat. Eum ut inventore ut et aliquid et dignissimos.', '2023-01-22', '2023-01-22', '2781.00', 'KES', '(984) 710-7277', 'jadyn53@yahoo.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(7, 'Eliezer Hodkiewicz', 'eos-qui-nulla-recusandae-rerum-ducimus-reprehenderit-sunt-perspiciatis', 'Possimus quo nulla sapiente voluptas voluptas ab. Fugiat qui earum quia unde adipisci dolorem laboriosam. Velit debitis fugiat suscipit sed deleniti. Laborum impedit rerum ut ad dolor vel qui id. Asperiores animi velit nam. Optio assumenda doloremque quibusdam repellat quia. Aliquam id beatae qui dolore et quod eos excepturi.', '2023-07-22', '2023-07-22', '2706.00', 'KES', '+1-657-365-4542', 'thalia43@dicki.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(8, 'Ramiro Kunze', 'nisi-et-non-ut-rerum-aut', 'Nisi dolores esse nulla ut quae officia neque at. Ipsum aut ipsum dolor commodi est. Est hic quas nobis. Quisquam suscipit iusto earum commodi consequatur. Ea aut sit ut dicta rerum. Ut nobis dolor quas ab. Excepturi sint consectetur saepe aut sed. Iusto id velit beatae nulla quos. Odit fuga minima autem. Quia dolor dolorum possimus ut fugit consequuntur.', '2023-05-22', '2023-05-22', '1663.00', 'KES', '331-613-3756', 'josianne.borer@marvin.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(9, 'Miss Tracy Schamberger', 'placeat-modi-provident-laborum-ratione-adipisci-eius', 'Sit dignissimos sit architecto. A aliquam quia quia facilis sint sit libero. Qui modi id accusantium accusantium tempora. Qui architecto occaecati numquam dolores maxime soluta. Consequuntur ullam saepe natus molestias. Mollitia qui quia minus cum. Impedit quis qui et sequi facilis provident et. In nulla quidem rerum sint. Molestias dolor sunt est deserunt repellendus. Mollitia autem dolores ullam impedit sunt distinctio et. Cupiditate tenetur magni dicta fugiat harum non.', '2023-06-22', '2023-06-22', '995.00', 'KES', '(774) 468-6377', 'eino.vandervort@armstrong.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(10, 'Wilburn Marvin', 'iste-id-voluptate-laboriosam-eaque-tempore-enim', 'Dolores eum rerum laudantium ipsa. Quis in dolor tenetur explicabo. Nobis sit voluptas voluptate rerum minus eaque veniam. Accusamus expedita qui unde qui ut dolorum quo. Et qui voluptas velit incidunt. Aliquid et recusandae odio voluptatem ipsam excepturi. Expedita explicabo maiores sed aut. At aliquam dolorum est quis quo. Aliquid reprehenderit recusandae praesentium omnis quis. Ex ipsum eum praesentium minima quidem ipsam vel.', '2023-05-22', '2023-05-22', '3788.00', 'KES', '+1-959-953-1300', 'vlegros@stark.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(11, 'Andreane Dickens', 'iusto-sed-inventore-natus-soluta', 'Qui consequuntur beatae cum est et. Similique quibusdam hic maxime quia. Culpa voluptatem facere voluptate sapiente quis laborum sint. Similique est aspernatur consectetur sit reprehenderit dolores inventore excepturi. Asperiores nemo ipsam ut architecto impedit porro cum. Dolorum ad temporibus excepturi dolores amet similique. Qui voluptate iure autem non velit sed. Sint officia aliquam sed occaecati veniam. Reprehenderit quia unde a cum.', '2023-09-22', '2023-09-22', '5218.00', 'KES', '+1-720-431-0279', 'obalistreri@hotmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(12, 'Therese Wiza', 'quidem-iure-natus-atque-commodi', 'Eaque nostrum a voluptates cupiditate ea veritatis. Aut molestiae sed quia expedita mollitia ab. Ipsa itaque consequuntur aut quia. Occaecati magni placeat omnis blanditiis vel. In rem facilis tenetur dolor in. Omnis harum quidem voluptatem sapiente nostrum ut quia. Quo saepe reiciendis ut dolorem provident vel similique. Soluta sunt aliquid sed corrupti. Aut minima nulla veniam possimus eos doloribus asperiores. Et sit pariatur et velit eaque vitae. Ipsa illo rem quis non blanditiis nisi. Quibusdam quasi quo ratione est nisi ipsam.', '2023-02-22', '2023-02-22', '2857.00', 'KES', '818.294.7307', 'leonora.marvin@ritchie.biz', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(13, 'Mr. Baylee Wisozk DDS', 'et-fuga-id-molestiae-consequatur-aut-aperiam-non', 'Voluptas eius animi voluptatum ipsam totam blanditiis. Aut quos dolores quia. Dicta perspiciatis maiores et totam. Consequuntur repellat deserunt omnis sit rem quibusdam inventore. Repudiandae et cupiditate eveniet odio accusantium unde. Provident illum ducimus ipsa sed omnis. Quia vel accusantium sit officiis corporis alias maxime aut. Et voluptates rerum enim laboriosam excepturi et. Dolores delectus consectetur nemo quasi iusto voluptas iure.', '2023-05-22', '2023-05-22', '2460.00', 'KES', '1-551-623-1342', 'treutel.everardo@hotmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(14, 'Jany Beier', 'non-laborum-aut-debitis', 'Laborum laborum fugiat harum accusantium sit. Omnis ipsam aut maxime molestias necessitatibus numquam aut. Molestias aut quis maxime saepe ducimus doloremque nisi. Illum amet quod ut laborum maxime cupiditate ut. Mollitia consectetur hic eligendi quae est repudiandae aliquam quia. Quia sed animi eos molestiae. Rerum libero est voluptatem accusantium.', '2023-09-22', '2023-09-22', '7215.00', 'KES', '(559) 666-2387', 'ekiehn@fahey.biz', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(15, 'Selena Bergstrom PhD', 'sed-nobis-enim-eum-occaecati-rem', 'Et eos quibusdam quas autem. Illo non animi sed asperiores dolorem. Vel unde ratione nostrum asperiores omnis est. Ducimus rerum qui est molestiae placeat et. Architecto nihil sit deserunt adipisci inventore corporis alias. Soluta qui est nobis non. Rem repudiandae dignissimos aspernatur architecto. Et nesciunt aut ratione.', '2023-06-22', '2023-06-22', '1570.00', 'KES', '757.861.2892', 'eliza.spinka@yahoo.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(16, 'Dr. Ariel Ziemann MD', 'quod-est-voluptas-necessitatibus', 'Ipsam sunt debitis voluptatem est tempora. Quibusdam vel voluptas consequuntur dolore ipsa eos vero est. Quisquam consequatur voluptates autem repellat. Nihil repellat ut voluptates sunt nihil sed sequi. Qui quaerat aut facilis sit. Incidunt assumenda veritatis exercitationem asperiores id qui rerum. Accusantium ut molestiae cupiditate sit. Quia veritatis sequi non necessitatibus quaerat. Quibusdam reprehenderit ex ab error. Aut natus delectus et. Laboriosam odit tempora quia qui omnis minima impedit. Ab exercitationem enim quod labore esse est. Tenetur eius doloremque fugiat voluptatibus mollitia facilis. Illo molestiae quibusdam voluptatum ut sequi porro voluptatem. Est sint tempore aut maiores sit aut.', '2023-09-22', '2023-09-22', '953.00', 'KES', '681.386.0608', 'jesse.sauer@lang.net', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(17, 'Ellie Gleason', 'soluta-quia-qui-qui-ad-laboriosam-qui', 'Doloremque veritatis quas eius blanditiis non ut eligendi. Quisquam ut repellendus reiciendis aperiam architecto dolores. Ipsa esse autem est voluptatibus officiis. Qui dolore corporis et enim nesciunt nihil. Voluptatem molestiae at mollitia est odit omnis. Possimus unde ratione sapiente molestiae. Quo sed aut sit alias. Expedita fugit exercitationem voluptatem quis impedit rerum animi. Non sunt quaerat quos. Earum expedita ut et assumenda assumenda qui sit dolorum. Quo veritatis est ratione et ipsam quisquam. Sunt vitae pariatur reiciendis ut. Omnis dolores nobis facilis cum est officia. Ducimus recusandae officiis eum quia officiis aut dolores quis.', '2023-02-22', '2023-02-22', '2919.00', 'KES', '412.266.0392', 'cjohns@fisher.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(18, 'Miss Albertha McClure', 'dicta-autem-sed-eaque-incidunt-officia', 'Et cumque aut aut placeat autem omnis magni. Et minima voluptatum nesciunt ipsam similique sint ea corrupti. Sit architecto sed hic quidem commodi. Et magnam ipsum fugit nobis ea et aliquam. Perspiciatis a rem earum ratione est et quis. Vero in commodi sit dolorum praesentium. Qui sequi nostrum quas aliquid non voluptatem.', '2023-04-22', '2023-04-22', '4341.00', 'KES', '1-606-910-9673', 'dave.waters@gmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(19, 'Miss Rachel Gleason DDS', 'accusamus-atque-enim-incidunt-quas-voluptas-animi-blanditiis', 'Sed inventore nulla fuga eos ullam. Et sapiente ut in. Eum delectus tempore sit expedita eum. Ut ut rerum et rem sit voluptatem pariatur. Et maiores saepe qui nobis cupiditate sunt quia assumenda. Architecto qui enim ut nisi dolor repudiandae. Dolor quia vitae est ut dolorem. Debitis maxime placeat facilis. Officia rerum molestiae nostrum at. Dolores non ab quibusdam necessitatibus vitae autem et. Illum sit aliquam voluptate cumque et eius. Maiores laborum quia delectus corporis qui officia quis.', '2023-01-22', '2023-01-22', '4027.00', 'KES', '+17755928543', 'duane.hammes@bednar.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(20, 'Tess Bernier', 'omnis-ipsa-occaecati-est-fugiat-eum-sapiente', 'Nostrum cupiditate quibusdam suscipit quasi hic sunt. Porro et ducimus iusto dolore magni. Officiis praesentium quo earum vel qui in nostrum. Dolor dignissimos repellat reiciendis architecto illo itaque. Iusto optio illo exercitationem soluta voluptatem velit. Amet quia dolor explicabo possimus ut ut ut. Possimus omnis excepturi culpa ipsa fuga. Deleniti magni sint commodi sit modi qui. Libero eveniet ipsa aut quibusdam voluptatum dolor vitae. Consequatur sed possimus fuga. Consequatur iste mollitia nisi.', '2023-03-22', '2023-03-22', '7678.00', 'KES', '+14786180309', 'bret51@yahoo.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(21, 'Camylle Schoen', 'aut-porro-nihil-dolor-cumque', 'Qui quaerat qui ut architecto qui. Quae ratione officiis nam at. Molestias rerum quis autem quo et expedita maxime. Dolorum non neque sit dolores dolorum. Quos qui occaecati quia consequatur. Libero neque neque est dolore. Esse quis quae voluptas odio quod commodi. Quam non ab fuga dolore.', '2023-06-22', '2023-06-22', '4523.00', 'KES', '+19808668761', 'legros.adriana@romaguera.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(22, 'Korey Batz', 'et-quia-vitae-iste-adipisci-iste', 'Atque rerum rerum voluptatem in ullam. Aut qui molestiae dignissimos ipsam molestiae odit. Et omnis est aliquam expedita tempora maxime dolore occaecati. Et autem ut velit repellat laborum at omnis. Perferendis eos dicta nihil exercitationem incidunt. Tenetur autem consequatur vel ratione. Vitae consequatur velit aspernatur laudantium. Quas voluptas pariatur voluptatem quo. Et esse veniam dignissimos ipsam commodi inventore vel rem.', '2023-02-22', '2023-02-22', '6106.00', 'KES', '+19387930529', 'boehm.winifred@gmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(23, 'Carrie Predovic', 'voluptas-illum-doloremque-sequi-non', 'Et quia quibusdam dignissimos temporibus reiciendis. Voluptates corrupti quia ullam. Cumque occaecati dolorum tempore magnam aliquid id non doloribus. Ipsum harum repellendus earum assumenda dolore aut itaque quisquam. Dolores fuga fugit quos modi est minima deserunt. Fugit deleniti doloribus iste qui reiciendis saepe. Velit dolorum iure nihil vel at. Libero autem mollitia qui quidem autem deleniti aliquam. Sapiente natus et molestiae.', '2023-01-22', '2023-01-22', '1123.00', 'KES', '+19478693803', 'mmurazik@ullrich.biz', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(24, 'Genesis Jacobson', 'totam-mollitia-velit-aliquam-adipisci-ad', 'Quis reiciendis dolor aut. Omnis in eos doloremque dolorum officiis perspiciatis. Dolor nam eveniet itaque. Non consequuntur qui omnis eum vel ut. Sequi sed id autem qui modi quae qui. Ut et harum deleniti culpa magnam ut placeat illum. Nemo nam alias nisi dicta ad sint. Voluptatum asperiores cupiditate velit vel tenetur harum. Est et tenetur ipsam eum ea rerum dolor. Velit et voluptas impedit voluptate. Voluptatem ex eius corporis debitis. Quod velit necessitatibus voluptate facilis ex et voluptatem. Rerum et rerum soluta aliquam. Neque vel excepturi quod cum.', '2023-01-22', '2023-01-22', '5163.00', 'KES', '(631) 803-3567', 'rwindler@yahoo.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(25, 'Eleonore Olson', 'incidunt-enim-saepe-dicta-sit-voluptatem', 'Quidem velit dolor quod assumenda iste. Quae nihil at et. Qui et ut repudiandae repellat. Perspiciatis laudantium sequi mollitia et facere. Ut ut voluptatibus natus doloribus. Blanditiis omnis quibusdam fuga labore est. Consectetur consequuntur debitis autem esse ea dolorum. Eligendi occaecati quisquam ut. Accusantium ducimus ut corporis deleniti perferendis atque expedita voluptatem. Aspernatur velit iure libero non praesentium ratione non dolores.', '2023-03-22', '2023-03-22', '856.00', 'KES', '+1-847-947-5750', 'edison47@weimann.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(26, 'Mrs. Aylin Friesen', 'in-qui-voluptate-qui-aliquid-autem-minus-et', 'Repudiandae reprehenderit ut nihil rem expedita. Et id quia placeat laboriosam sint et ullam perspiciatis. Molestias accusamus quasi occaecati. Dignissimos laudantium aspernatur doloremque reiciendis et vitae. Quia rem rem aut eos. Sed qui nihil sint et et consequatur. Totam ea suscipit quo. Nisi ducimus autem officiis dolorem est. Et modi numquam hic alias non. Perferendis voluptatem sit velit tempora. Ut iure voluptatibus et ut tempora. Sint cumque et cum nemo rerum commodi neque aut. Quibusdam quisquam quia qui nesciunt.', '2023-02-22', '2023-02-22', '7621.00', 'KES', '+19209786282', 'ledner.margaretta@gmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(27, 'Bonita Erdman PhD', 'tempora-recusandae-doloribus-voluptatem-nihil-laborum-eius', 'Optio minima sed vel occaecati dolorem. Ut quam voluptas harum voluptatem vel illum. Laboriosam soluta eveniet id est. Molestiae omnis aut animi quidem. Sunt quod qui quia ea. Et ut qui consequatur id accusantium suscipit commodi. Nulla illum qui est. Nisi quia odio fuga minima et consequatur. Commodi a cumque perspiciatis eum dolorem consequuntur quaerat. Laborum libero iste ratione ab omnis iusto. Neque nihil quis voluptatem deleniti recusandae quasi nihil. Quis officiis repellat voluptatum qui. Cumque dolores tempore totam ipsum nihil nemo.', '2023-05-22', '2023-05-22', '3075.00', 'KES', '1-434-864-5008', 'chase.sporer@yahoo.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(28, 'Jeramie Grimes', 'voluptas-pariatur-nam-quo-dolores', 'Officia expedita architecto porro expedita aut illo. Minus quibusdam provident saepe doloremque libero illum. Ad optio rerum vel sequi est pariatur eum. Exercitationem consequatur odit voluptate architecto explicabo. Iste maiores accusamus voluptatem ex qui eveniet molestiae nihil. Dolores voluptatem veniam quis repudiandae. Sed sapiente vel praesentium sed ex. Et laboriosam quis voluptas asperiores.', '2023-05-22', '2023-05-22', '898.00', 'KES', '917.922.3424', 'xbednar@mccullough.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(29, 'Shaina O\'Keefe I', 'sit-sit-quia-ut-pariatur', 'Quia aut quod ipsum sed harum hic. Quia voluptates maxime fugiat. Recusandae beatae suscipit minus quam. Minus quo omnis excepturi eum sed eos. Vel maiores officia rem corporis praesentium ducimus sit. Repudiandae quia qui aut omnis dicta. Nostrum est odio occaecati autem. Veritatis atque voluptas nisi quidem sit.', '2023-02-22', '2023-02-22', '6219.00', 'KES', '(680) 558-7154', 'hassie13@gmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(30, 'Mr. Caden Paucek', 'vitae-aspernatur-laborum-quibusdam-voluptatum-eum-temporibus-et', 'Distinctio nihil quisquam est et sapiente assumenda accusantium. Enim amet maiores aspernatur. Deleniti dolore voluptatem tenetur sed. Qui libero explicabo praesentium consequuntur dolores. Suscipit tempora dicta dolor consequuntur nisi quam omnis. Est qui provident voluptas sapiente ullam suscipit culpa. Et et sunt doloribus maiores reprehenderit ratione.', '2023-08-22', '2023-08-22', '1764.00', 'KES', '(629) 451-4054', 'alisha.steuber@gmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(31, 'Winona Beer Jr.', 'consequatur-exercitationem-sunt-eum-placeat-corrupti-ullam-et', 'Et qui ea eaque explicabo vel ullam ut. At voluptatibus sunt facilis quia temporibus suscipit. Quod ut recusandae cumque. Accusamus quia deserunt quam eum asperiores omnis. Voluptates maiores reiciendis sint enim repellendus et ratione modi. In asperiores ad et quia ipsa debitis consequatur. Placeat quaerat quis quis ut. Sed quo non voluptatem dolorem nam fugit similique. Numquam recusandae adipisci et aperiam in cum veritatis. Illo magni quod quasi omnis. Aut veritatis temporibus autem et aut dolorem.', '2023-09-22', '2023-09-22', '5330.00', 'KES', '1-732-621-1393', 'sheldon95@yahoo.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(32, 'Maritza Torp I', 'doloribus-qui-odit-voluptas-autem-a', 'Dolores ut in possimus odit. Minus ea dolores alias quia impedit ratione. Quam aut necessitatibus laboriosam sint. Autem voluptas voluptatem illo laudantium. Quia dolore et quae quis aspernatur. Sequi laboriosam doloremque occaecati ducimus. Aut eos occaecati ut asperiores nobis. Deserunt corrupti vel autem occaecati. Dolor ab ea nihil voluptatem voluptatem.', '2023-07-22', '2023-07-22', '5428.00', 'KES', '+1-989-226-0347', 'qshields@west.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(33, 'Mike Herman', 'hic-est-commodi-ea-harum-saepe-voluptatem-non', 'Quas ipsa qui molestiae atque dolores molestiae. Et libero est sed officia iusto quaerat eum. Iure ea amet dolor deserunt. Corrupti enim magni blanditiis aut. Placeat optio fuga vitae eum quos. Eaque qui repudiandae minima magnam praesentium quo aspernatur. Sit ipsum perferendis ut voluptas sit alias natus.', '2023-04-22', '2023-04-22', '7979.00', 'KES', '781.814.5583', 'bzemlak@collins.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(34, 'Dr. Gideon Quitzon', 'nobis-quia-asperiores-exercitationem-consequatur-omnis', 'Quod exercitationem nostrum quo quas eos accusamus minus. Facilis earum est dolorem tempora adipisci nemo. Eum illo voluptate cupiditate iure. Nihil aliquam esse maxime aut dolore. Eum in quos est laudantium labore. Natus nulla autem corrupti eligendi. Consequatur omnis hic veritatis sit dolores porro qui. Cumque neque aperiam est sit alias nulla excepturi.', '2023-09-22', '2023-09-22', '5304.00', 'KES', '571-514-8948', 'uromaguera@kemmer.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(35, 'Jennings Crona', 'facilis-dolore-eveniet-odit-est-facilis-rerum', 'Quisquam accusamus mollitia iusto quidem. Ut et voluptas voluptates delectus nobis inventore voluptates. Nobis laborum necessitatibus voluptatibus magnam corrupti. Est rerum labore laborum et culpa explicabo quia. Ipsa eveniet et animi quos aut. Vitae pariatur laboriosam et eum. Nobis quo cumque nostrum atque autem incidunt quisquam.', '2023-07-22', '2023-07-22', '1976.00', 'KES', '+1 (352) 363-6417', 'janie.considine@hahn.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(36, 'Lawson Luettgen', 'qui-tempora-consequatur-dolor-aperiam-aut-pariatur', 'Magni est illo facilis officia dolorem. Consequuntur distinctio aut molestias similique. Possimus repellat dolore quaerat natus repudiandae. Accusamus aliquam impedit esse minima dolorem. Ut laudantium in consectetur ab voluptatum assumenda unde. Ut molestias rerum consequuntur pariatur mollitia cumque. Sed et perspiciatis nostrum aut. Pariatur voluptatem occaecati sint voluptatem. Autem vitae nostrum assumenda nesciunt maxime sequi. Facere nobis occaecati soluta nemo ipsam consequatur. Error ut omnis aspernatur eius hic ea ut reiciendis. Odio consequatur voluptates nihil voluptas assumenda blanditiis rerum ratione.', '2023-09-22', '2023-09-22', '1552.00', 'KES', '254-823-5319', 'ivory36@hotmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(37, 'Mr. Clinton Stracke', 'perferendis-similique-unde-ipsam-alias', 'Cum sed nam ut et quaerat accusantium nesciunt. Laborum et iste rerum. Ut doloremque excepturi nihil reiciendis quidem. Dolorem qui distinctio et eum magni. Esse nobis provident atque enim molestiae nisi. Mollitia labore odio possimus modi vero magni nihil. Accusamus repellendus saepe quia sint qui. Velit voluptas distinctio accusantium architecto in voluptas qui dolorum. Sunt dolor iusto reiciendis praesentium occaecati qui. Voluptate iusto eum qui culpa. Laudantium qui ipsam cumque minima repellendus assumenda quod. Quia ducimus voluptatem dolores. Dolore est laborum non corporis quo qui dolor ad. Id voluptatem sit atque neque tenetur nam dolor. Rerum commodi ea et.', '2023-09-22', '2023-09-22', '3263.00', 'KES', '(240) 430-3080', 'breanna.medhurst@altenwerth.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(38, 'Linnea Tremblay', 'iste-sunt-at-quis-ut-explicabo-mollitia-voluptatem', 'Enim dolores inventore quis officiis voluptate. Distinctio quaerat libero velit. Neque quia labore saepe deleniti beatae sapiente. Nostrum alias enim occaecati vel. Aut illum cupiditate blanditiis adipisci. Ut blanditiis cupiditate eaque. Consequatur non est commodi excepturi deserunt. Accusantium facere fuga eveniet incidunt nihil est rerum.', '2023-01-22', '2023-01-22', '5516.00', 'KES', '406-239-6416', 'eusebio98@hotmail.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(39, 'Maya Nicolas I', 'cupiditate-totam-ut-et-iusto-et', 'Dolorum neque esse debitis molestias. Amet nihil ipsum sequi aut molestiae ut dolor. Commodi at aliquid dignissimos consequatur veritatis aliquid aut. Dolorum voluptatem enim omnis rem esse blanditiis. Saepe at facilis laboriosam. Quis veritatis ad ut natus rem rerum. Officiis commodi veniam aspernatur ut. Deserunt excepturi ipsa consequuntur quas placeat illum. Et sed qui porro ea itaque est sequi. In et debitis in vero. Et consequuntur distinctio deserunt cum suscipit et. Quia provident consequatur aperiam dicta. Doloribus molestias eos accusamus architecto soluta. Sint ipsa voluptatem illo mollitia.', '2023-09-22', '2023-09-22', '4546.00', 'KES', '828.922.7204', 'schowalter.shayna@hotmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(40, 'Aliya Runolfsdottir', 'et-quia-temporibus-dolor-est-enim-est-veritatis', 'Voluptates eos nobis repellendus et dignissimos dolorem reprehenderit ab. Provident commodi cumque eum nisi voluptatem nesciunt. Nesciunt culpa sint omnis et porro quidem. Illo fuga et cum sed pariatur. Ut beatae ipsum non fuga sed. Repellendus vel occaecati alias veritatis aperiam tenetur. Dolor corporis sunt totam deserunt esse amet sed.', '2023-01-22', '2023-01-22', '4280.00', 'KES', '(820) 326-3850', 'koss.darby@yahoo.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(41, 'Travon Nader', 'tempora-corrupti-omnis-nostrum', 'Cum nemo eius soluta voluptatem. Ipsa quasi quia repellendus ad. Sed ullam sit et sit. Sequi blanditiis aperiam incidunt labore. Harum voluptas fuga voluptate iusto enim ullam. Neque error ut saepe est culpa adipisci quisquam. Laboriosam eum fuga dignissimos aliquid incidunt. Qui laudantium maiores voluptas enim consectetur pariatur. Est commodi omnis et sed non est nihil. Omnis corrupti ea explicabo debitis explicabo. Reiciendis at et et rerum voluptas quasi. Ad culpa aperiam dolorem dignissimos quam.', '2023-07-22', '2023-07-22', '763.00', 'KES', '+12722674933', 'zweissnat@wilkinson.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(42, 'Mr. Conner Marquardt', 'vitae-ut-dignissimos-ea-repellat-eum-sed-ea', 'Sint consequatur eligendi molestiae rerum eligendi. Sed repudiandae consequatur dolorem repudiandae quaerat. Sed quibusdam maiores quia. Voluptatibus officiis dicta voluptatum libero suscipit architecto facilis. Molestiae autem adipisci nihil odit temporibus nobis nemo. Consequatur aliquam harum aut. Dicta dignissimos fuga quia dolores ea atque accusamus consequuntur.', '2023-01-22', '2023-01-22', '888.00', 'KES', '+1-678-307-4346', 'dominic72@cassin.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(43, 'Dr. Ibrahim Kunde V', 'cupiditate-repudiandae-quam-cumque-recusandae-sit-minima-facere', 'Assumenda magnam vel quae aut. Explicabo assumenda voluptas dolores harum. Dolor nemo omnis atque nesciunt nisi atque. Magnam nobis sit id illum. Esse voluptates ea mollitia. Pariatur voluptate consequatur fugit voluptatem harum repellat inventore voluptates. Saepe sit aliquam voluptatibus suscipit. Iste ut eos nihil ut sapiente accusamus doloribus. Omnis et consequatur inventore incidunt dolores tempore aut. Ea vel ipsum aut. Officia placeat voluptatem et quod magnam dolores suscipit. Et omnis atque praesentium consequatur nobis. Tempore nobis maiores deserunt tempore consequatur. Quae qui perspiciatis dolore beatae vero quo eveniet.', '2023-03-22', '2023-03-22', '4694.00', 'KES', '+1-318-782-1466', 'zschaden@huel.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(44, 'Wilson Gleichner', 'explicabo-illum-et-et-unde-nisi-officia-sint', 'Quidem optio eveniet rerum explicabo. In veniam alias quia nihil quisquam molestias voluptas. Rerum debitis voluptate tenetur vero. Eveniet eaque minima officiis. Iusto quia id minus repellat. Soluta quaerat qui eum molestiae. Ratione quis voluptas incidunt consequatur tempora iusto qui. Dolores et sunt iusto. Fuga aut sed dolores fuga. In quaerat incidunt et ut sunt dolorem quam enim. Qui rerum suscipit soluta. Repellat sunt sunt veritatis qui quae ad itaque. Quam ratione hic praesentium dolorem.', '2023-02-22', '2023-02-22', '2833.00', 'KES', '240-977-1504', 'lemke.kailyn@keebler.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(45, 'Dr. Edna Bradtke', 'aperiam-labore-minima-qui-enim-ut-excepturi-error', 'Vel quia adipisci autem corporis maxime consectetur qui. Autem dolor non ut assumenda nihil. Voluptates quam ut officia aspernatur. Et omnis est ut qui pariatur. Ut tenetur dolor tenetur et qui ducimus. Consequatur voluptatem iste ipsam doloribus impedit facere. Omnis ut et cumque repudiandae sed. Fuga et officia ut tempora dolorem. Ea voluptates odio distinctio veniam error aperiam. Eaque vel sed velit dolorem incidunt.', '2023-07-22', '2023-07-22', '2293.00', 'KES', '+1 (617) 377-9014', 'earlene.douglas@lowe.info', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(46, 'Dale Torp', 'autem-est-dolor-impedit', 'Dolor rerum quo et quasi et praesentium. Voluptas modi neque ut voluptates ad provident. Cum iure ullam eos optio quam corrupti cumque sit. Qui asperiores ab voluptatem laboriosam aut architecto alias. Voluptas accusamus illum a dolorem dolorum. Qui illo quam unde quae suscipit. Pariatur alias suscipit quia eos incidunt quia ea.', '2023-07-22', '2023-07-22', '862.00', 'KES', '318-949-5797', 'heath13@gmail.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(47, 'Lincoln Parker', 'deleniti-quia-officiis-eligendi-sed', 'Est voluptas voluptatibus accusamus perspiciatis accusamus. Nihil tenetur nemo amet dignissimos et. Qui doloremque et et et enim quod vero officia. Molestiae eum commodi et cum labore est. Dolor ut quia autem perspiciatis porro. Non doloremque dolore in sed. Et distinctio ea perspiciatis dolor eos inventore mollitia. Amet incidunt tenetur dolore voluptatem molestias. Consequatur suscipit enim laudantium sed. Eos consequatur nobis et et suscipit beatae soluta.', '2023-02-22', '2023-02-22', '1683.00', 'KES', '+15407886916', 'mathias.mckenzie@gmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(48, 'Mackenzie Halvorson', 'reiciendis-modi-expedita-asperiores-ut-rem-quibusdam', 'Rerum ex ipsa quia esse velit provident officiis. Inventore ducimus quia corrupti nam suscipit. Nihil non suscipit maiores maxime. Facere et voluptatem error. Ab cum exercitationem molestias quam repellendus. Aut quia cumque saepe voluptatibus odit. Est maxime debitis alias cupiditate. Ex harum qui deleniti.', '2023-05-22', '2023-05-22', '7591.00', 'KES', '484-498-1095', 'delilah.moore@krajcik.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(49, 'Mariela Kassulke', 'beatae-necessitatibus-officiis-et-dolore-ut-cum', 'Quia voluptatem aperiam numquam minus corrupti voluptatem. Laborum eum nihil non aliquid natus dolores cum. Tempore dolores rerum neque mollitia aut reprehenderit. Numquam fugit repellat facere quasi magni alias est exercitationem. Et veniam repellendus consequatur delectus. Consequatur dolorem vero est suscipit et consequuntur unde. Eum consequatur sed sed eligendi ut inventore est. Voluptate quia id pariatur facere deleniti dignissimos. Enim qui numquam ex autem itaque.', '2023-03-22', '2023-03-22', '3295.00', 'KES', '+1-806-423-7188', 'lockman.kaya@boehm.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(50, 'Shyann Nolan', 'consequatur-rerum-esse-odit-corporis', 'Dolore odio aut sed quis cum. A explicabo doloribus doloribus. Quas itaque praesentium et. Exercitationem ea est cum non porro dolorem et quam. Eligendi incidunt eos aut possimus sapiente. Laboriosam id eligendi totam. Ipsum expedita et aspernatur dolorem deserunt aut. Harum deleniti eos est et modi. Nobis optio ea quia.', '2023-01-22', '2023-01-22', '7537.00', 'KES', '952-540-5578', 'theron.hamill@gmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(51, 'Elvera Kuhic', 'veritatis-debitis-impedit-qui-nemo-eum', 'In voluptas quia illo voluptatem. Odio dolor in et sapiente saepe non neque. Quis provident maxime excepturi eum saepe nulla excepturi. Debitis dolore ut inventore labore. Non quis officiis odit odit enim ipsum. Ipsum similique voluptatum unde dignissimos ut. Illo esse veritatis voluptas nobis alias. Blanditiis aperiam ducimus sapiente repellat tempora. Soluta quia fugit beatae illum ut maxime ipsum.', '2023-03-22', '2023-03-22', '7847.00', 'KES', '1-515-223-8722', 'janessa87@gmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(52, 'Rosalee Thiel', 'autem-repellat-rem-rerum-officiis-possimus-excepturi', 'Vel tempore minus eaque. Eum fugiat ducimus est maiores. Cum et laborum consequatur aliquam ut tempora totam. In magni rerum alias aut sed. Et numquam animi rem doloribus assumenda unde. Officia animi sunt itaque odit. Aspernatur aperiam facilis facere suscipit dolores eius dolorem perspiciatis. Temporibus consequuntur qui facere vero dolorem quaerat nobis. Aut esse eos eligendi similique aspernatur dolorem placeat. Totam quasi animi debitis a. Quis odit et illum consequuntur eaque eum voluptatem. Dolor voluptatem dolore quia officiis sint totam omnis voluptates.', '2023-04-22', '2023-04-22', '6146.00', 'KES', '+1-223-448-2398', 'svonrueden@orn.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(53, 'Mr. Mose Bins', 'sapiente-itaque-ut-id-optio', 'Rem quia quia architecto officiis tempore ipsa. Assumenda harum optio id aut sit nisi. Quae ut minima et provident provident non deleniti. Enim id reprehenderit et inventore impedit. In illo qui iste dolorem. Eligendi vel delectus a ipsa dolorum quos. Culpa vero qui voluptate excepturi nostrum. Et dicta excepturi soluta qui perferendis. Aut dolorem aut voluptatem minus et rerum velit. Ut dolores laboriosam hic quis. Atque rerum et voluptatum assumenda ipsam. Vel pariatur voluptas nulla repellat omnis voluptatem eligendi adipisci.', '2023-06-22', '2023-06-22', '7153.00', 'KES', '+1-386-657-9072', 'ankunding.martina@gmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(54, 'Prof. Cayla Lehner', 'nesciunt-fugiat-illo-aut-deleniti-placeat', 'Impedit officiis ut enim voluptas quaerat. Reprehenderit iusto perspiciatis qui sed. Vitae inventore asperiores iure incidunt sapiente inventore. Et nesciunt ut laudantium et est. Doloribus ad ullam sapiente ut facilis ullam eos. Dicta harum quia sed. Eaque autem corrupti quibusdam occaecati. Voluptatibus explicabo illum laboriosam doloremque consequuntur. Velit consequatur ut voluptatum quae. Doloremque nihil similique accusantium in. Aut esse voluptatum delectus porro excepturi quidem ut. Ad qui officia qui odio qui in officia sit. Ea officiis omnis fugiat quia dolorem.', '2023-06-22', '2023-06-22', '848.00', 'KES', '618-214-6510', 'nlarson@cremin.info', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(55, 'Angie Mitchell', 'voluptatem-eos-perspiciatis-impedit-repellendus', 'Eos culpa et dolorem quo consequatur. Hic et ut sed doloremque magni quae. Amet omnis et voluptatem vero. Amet praesentium reprehenderit qui dolores. Asperiores delectus ullam molestias. Incidunt dolor saepe eaque sequi quo consequatur voluptatem. Temporibus nobis ipsa rem sit libero sunt. Sunt dolorem corrupti et dolor suscipit. Non ipsam veniam est aut. Ipsa vitae aut veniam sed nostrum ut.', '2023-04-22', '2023-04-22', '2551.00', 'KES', '339.667.0066', 'fausto.pollich@gmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(56, 'Dr. Kylie Swift', 'molestiae-quo-sed-est', 'Aut sapiente asperiores et laborum quis. Voluptatem repudiandae voluptatem dolor quas incidunt et commodi. Ut sapiente modi aperiam aliquid molestias eum tempora. Explicabo quia reprehenderit fugiat et itaque sunt ducimus ipsam. Rerum id distinctio cumque quia voluptas. Ea placeat omnis totam. Deleniti aut consequatur quas impedit aut cupiditate iste.', '2023-08-22', '2023-08-22', '2868.00', 'KES', '817-530-9451', 'cummerata.tess@yahoo.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(57, 'Prof. Hobart Ferry', 'sed-saepe-quisquam-magnam-corporis-omnis-dolorum-et', 'Officiis odit perspiciatis facere dicta et sunt dolorem. Quia inventore aut explicabo aspernatur nihil. Est molestiae rerum quod distinctio praesentium dolorum. Reiciendis autem quas quia voluptatem eum. Aut aliquid expedita libero aliquam fugit minus. Sed inventore ducimus dolores esse blanditiis non qui. Veniam quia repellendus architecto sit dignissimos. Qui alias consectetur voluptatem non at enim architecto. Sint aut doloremque autem omnis dolorum voluptatibus iure. Occaecati harum sit veritatis sed consequatur enim. Ut voluptate non exercitationem accusantium quos vel.', '2023-07-22', '2023-07-22', '6061.00', 'KES', '+18126915352', 'janelle.schmeler@hotmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(58, 'Viola Schamberger', 'adipisci-asperiores-id-aut', 'Earum voluptas animi consectetur. Sit ea molestias incidunt minus qui fuga laborum laudantium. Ut ea iure sint consequatur. Aspernatur deleniti et inventore distinctio dolor deserunt. Minus sit explicabo illo in et ab eius. Beatae cum laborum et porro deleniti in occaecati. Molestiae earum adipisci nihil sunt quaerat voluptas voluptatibus iure. Harum alias quod tempora. Consequatur sapiente consequatur sit ut distinctio vitae dolorem.', '2023-09-22', '2023-09-22', '7038.00', 'KES', '(231) 752-6886', 'kuphal.greg@yahoo.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(59, 'Werner Morissette Jr.', 'amet-earum-laboriosam-numquam-consequuntur-ipsam-tempora-et', 'Sed et voluptates rem quo eaque. Cum at dolor occaecati quisquam voluptatem. Debitis sequi aspernatur nihil quas error. Ut dolor exercitationem explicabo adipisci accusamus accusantium. Rerum deserunt magnam aut consectetur optio eum odit. Consequatur rerum velit soluta sit nam sit. Dolor laudantium dolor asperiores autem praesentium illum. Quidem quisquam sit laudantium nihil facilis blanditiis eligendi. Incidunt magnam quas voluptatibus voluptas minima.', '2023-07-22', '2023-07-22', '3036.00', 'KES', '+1 (434) 827-5729', 'astark@wolf.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(60, 'Mrs. Shaina Bosco DDS', 'magnam-dolor-sapiente-vel-molestiae-nobis-voluptatum-voluptatem-assumenda', 'Doloremque quaerat ut nam. Consequatur nobis dolores provident eum porro sapiente. Et voluptatibus ut aliquid consequatur eveniet. Quia vero voluptatem cupiditate ducimus aperiam laboriosam. Nam voluptas ipsa doloribus vitae minima quasi ullam. Sit aut molestias eum dolores non. Ab reprehenderit in consequuntur odio quae explicabo impedit aliquid. Eum fugiat nesciunt magni sit dicta minima animi ipsum.', '2023-07-22', '2023-07-22', '4721.00', 'KES', '1-609-206-9842', 'wrowe@balistreri.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(61, 'Brandi Osinski', 'debitis-beatae-aut-omnis-dolorem-ad', 'Nostrum dolores omnis et dolorem id omnis. Occaecati repellendus enim quae quibusdam iure doloribus odit. Blanditiis repudiandae reiciendis aliquam in impedit quia. Doloremque ut totam vel vitae debitis quisquam. Ut quasi voluptatibus aut at. Laboriosam eius illo expedita doloremque. Modi eveniet consequatur est ut.', '2023-01-22', '2023-01-22', '4452.00', 'KES', '(248) 984-6012', 'madelynn81@schmidt.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(62, 'Prof. Blaise Crist Jr.', 'rem-debitis-qui-illo-sapiente-adipisci-itaque-dignissimos', 'Deleniti atque voluptatem aut et. Vitae veniam fugiat quod. Voluptatem recusandae quam est omnis pariatur. Sed officia numquam explicabo quos. Similique aut ea nam rem vel aut. Quas enim non laudantium autem officiis eum. Asperiores voluptas debitis fugiat dolores nostrum et eos a. Reiciendis fugiat numquam voluptatem magnam praesentium ea.', '2023-09-22', '2023-09-22', '3480.00', 'KES', '479-954-9608', 'major.morar@hotmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(63, 'Samson Anderson', 'ut-quia-et-tempora-aliquid-voluptatem-consectetur-sit', 'Laudantium iste sapiente in quis rerum. Sapiente eaque reiciendis autem. Molestiae eum illo non et quis id. Itaque architecto accusantium consequatur. Quis nobis quidem sed. Corrupti debitis dolor asperiores nihil illo dolor aperiam. Ea ea labore voluptate magni eos placeat. Eligendi amet eum illo rem error. Enim porro est minus dignissimos. Consectetur soluta similique facere qui illo dolores. Ipsam hic placeat architecto occaecati aut eveniet reiciendis ut. Inventore libero nobis in magni officia rerum quia. Atque incidunt debitis quaerat. Numquam optio ea alias iusto.', '2023-04-22', '2023-04-22', '6976.00', 'KES', '+1-828-932-2247', 'denesik.chandler@herzog.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(64, 'Mr. Brendon Koch IV', 'tenetur-accusantium-blanditiis-sit-dolor', 'Qui corporis atque nam assumenda provident vel qui reprehenderit. Sed repudiandae eaque aut dolore quia ut tempora saepe. Quasi non dicta a impedit possimus. Omnis consequatur culpa dolor perspiciatis. Dolor repudiandae laudantium doloremque facilis amet voluptatem totam. Eveniet error quia reprehenderit in iste. Dolorum fugiat rerum dolores facere. Quis dicta possimus numquam officia consequuntur occaecati sed vero. Tempora quam minus cum temporibus quam. Voluptatem ut debitis eos. Molestias et rerum et aspernatur distinctio voluptatem ducimus.', '2023-03-22', '2023-03-22', '3632.00', 'KES', '1-878-695-7498', 'coy.lakin@hotmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(65, 'Pablo Marquardt', 'voluptatem-omnis-adipisci-cupiditate-enim-magnam-aspernatur-culpa', 'Eum occaecati qui dolor. Ratione omnis qui sit ad qui enim ad ut. Et unde iste nesciunt aliquam est veniam. Itaque quos voluptatem odio. Et expedita dolore et ut. Nemo consequuntur eius expedita corrupti consequuntur dolor. Vitae nisi et maiores reiciendis repellendus eum. Corporis aut provident saepe voluptatem corporis laborum sint. Fugiat amet autem placeat quis ipsam soluta. Quos aut vel est dicta sunt. Voluptas eos rerum voluptatem doloremque at sunt a. Ut voluptatem sunt asperiores accusantium sit aut. Magnam maxime dolor neque consectetur veniam quam. Aut in non adipisci hic consequatur.', '2023-06-22', '2023-06-22', '2777.00', 'KES', '+1.223.795.9488', 'elmo69@hotmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(66, 'Leonel Mann', 'dolor-voluptates-molestiae-praesentium-sit', 'Natus repellat corporis neque repellendus autem officia omnis. Fuga est perferendis placeat molestiae numquam culpa. Adipisci aut et vel ad. Omnis vitae sed cumque beatae voluptates et. Aut ea et quo optio. Ut dolorum perferendis molestias in consequatur ea eaque voluptatem. Ut velit autem consequatur rerum consequatur facilis. Velit delectus esse saepe dicta. Reiciendis quaerat eligendi error nostrum non blanditiis assumenda. Vitae excepturi nisi quaerat et omnis totam. Vel et cumque similique sit.', '2023-02-22', '2023-02-22', '850.00', 'KES', '1-743-566-3640', 'haylee.mcclure@mueller.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(67, 'Marvin Wilkinson', 'dolores-est-modi-ut-esse-fugiat-quam', 'Dolorem quam facilis in architecto voluptas illo excepturi. Ut odio rerum assumenda. Et sed dicta velit labore est. Commodi qui consequatur qui quis. Quo sint dolores harum incidunt hic. Et et quod earum qui et ducimus. Soluta id est quia. Vero soluta quis eveniet maxime quo. Explicabo quo praesentium atque labore fugit magni. Aliquid quia delectus maxime eos quis. Ut aliquam enim repellendus expedita voluptas. Cum enim ab iure. Natus qui et qui soluta.', '2023-02-22', '2023-02-22', '1638.00', 'KES', '+1-680-299-3845', 'stokes.dangelo@hotmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(68, 'Ms. Bettye Runolfsdottir', 'occaecati-distinctio-repellendus-ipsam-cumque', 'Necessitatibus placeat magnam quasi. Suscipit harum quibusdam repudiandae aliquam adipisci illo. Culpa omnis consequatur ut illo. Eum atque molestiae voluptatem perspiciatis error. Quam hic ut qui labore qui. Repellendus non iusto expedita rerum ut voluptatibus. Enim fuga id ut iste quo vel. Commodi quaerat cupiditate dolor voluptas aut repellat. Dolore ut maxime aut quisquam ut minus quia. Culpa veniam rerum saepe fuga labore. Mollitia in beatae velit totam. Doloribus architecto aspernatur dolor laudantium aut expedita tempore quaerat.', '2023-08-22', '2023-08-22', '1850.00', 'KES', '510-277-5693', 'willa13@hettinger.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(69, 'Harrison Stehr', 'minus-consectetur-enim-perspiciatis-atque-similique', 'Consequatur quod natus voluptas laborum. Aliquam rerum rerum quidem eum voluptates molestiae ab. Rerum aliquid impedit odit quidem esse accusamus. Vel nemo aspernatur cum quas odit beatae ex. Esse dolores voluptates ducimus ut aut animi. Velit ipsum aut ab sit enim molestiae quod. Odit omnis deleniti praesentium expedita eum nostrum ad. Dolores nam hic rerum expedita nemo. Aliquid neque omnis sapiente quas. A quia assumenda velit nam ut et. Impedit ut illo aliquam sit cum repellendus quisquam vitae. Consequatur harum accusamus qui sed dolorem expedita nisi. Et eius praesentium suscipit rerum reprehenderit dolores.', '2023-07-22', '2023-07-22', '4375.00', 'KES', '+15207779127', 'mhills@hotmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(70, 'Dr. Johnathon Ratke', 'dolores-molestias-excepturi-et-repellendus-repellendus-autem-dolore', 'Porro et dolor quisquam velit quos mollitia soluta. Quod est maxime voluptas voluptatum. Ea maxime dignissimos sed sapiente. Neque ut sequi placeat doloremque vitae nostrum quo laboriosam. Quos facilis sapiente laboriosam voluptatem cumque maiores sequi eligendi. Quia perspiciatis repellendus laborum porro. In accusantium eaque labore rerum ab quasi odio. Sunt quis voluptate tempora.', '2023-01-22', '2023-01-22', '3817.00', 'KES', '+1.205.544.3441', 'walker.rosamond@yahoo.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(71, 'Colleen Roberts', 'qui-dignissimos-tempora-sunt-nisi', 'Dolor maiores rerum aut architecto unde et sit. Ratione illo recusandae non dignissimos earum et eos. Quasi facere dicta ipsam facere labore. Veniam est commodi doloribus. Voluptates necessitatibus perferendis numquam eveniet facilis fuga sunt. Omnis at corrupti qui dignissimos laudantium aut dignissimos. Sunt nulla veritatis laborum alias voluptatem perspiciatis commodi.', '2023-05-22', '2023-05-22', '7166.00', 'KES', '+1-239-321-6182', 'reina13@miller.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37');
INSERT INTO `products` (`id`, `title`, `slug`, `description`, `date_online`, `date_offline`, `price`, `currency`, `mobile`, `email`, `category_id`, `image`, `order`, `visible`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES
(72, 'Dr. Ottis Will V', 'corporis-et-quisquam-quia', 'Libero explicabo nisi quod molestiae magnam at. Libero sapiente deleniti laborum aut quidem reiciendis maxime. Repudiandae est et natus aut. Quibusdam aut dicta expedita sed. Vel temporibus minima cupiditate rem quia neque id. Aliquam aut autem ab magni sed excepturi excepturi. Sit id quia corrupti ex enim impedit nihil voluptatum. Est voluptas voluptatem deserunt maxime fugit. Omnis voluptates velit accusantium alias. Quaerat eaque aut doloribus est qui asperiores. Omnis consequatur dolorem vel distinctio minus similique. Quis inventore sit ut delectus temporibus. Incidunt similique tempora aut consectetur nobis dolor.', '2023-09-22', '2023-09-22', '5873.00', 'KES', '(470) 886-3241', 'rbernhard@hotmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(73, 'Ayla Kerluke', 'illum-cumque-ut-laudantium-rerum-ut', 'Omnis architecto tempore architecto nemo magnam quisquam inventore. Autem est sint aspernatur consectetur a et. Debitis harum pariatur ut veniam aut. Delectus velit animi numquam illo sequi. Laudantium laboriosam sint eius praesentium autem asperiores repudiandae temporibus. Laudantium aut atque eveniet necessitatibus id ex quis. Aut et voluptatibus eveniet libero voluptatem. Cupiditate quod enim inventore id quod perspiciatis non. Qui repellendus inventore quia et et repellat.', '2023-08-22', '2023-08-22', '2568.00', 'KES', '(947) 920-2385', 'nrohan@shanahan.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(74, 'Prof. Juvenal Walter', 'ad-voluptatibus-ipsum-esse-debitis-ut-minus-tempora', 'Consequatur eveniet porro quas eum dolores nihil. Assumenda odit consequatur aut eos perspiciatis. Eum nisi ut consequatur consequatur. Quaerat autem repellat qui fugit optio. Quidem harum eveniet enim nulla enim quae. Sunt atque sit itaque eos delectus optio. Enim blanditiis et ratione. Et molestiae consequatur est.', '2023-08-22', '2023-08-22', '5515.00', 'KES', '845-245-2424', 'conroy.orpha@gmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(75, 'Dr. Micah Wolff', 'natus-distinctio-tenetur-ipsam-ad', 'Mollitia rerum sunt similique eos natus aut. Maiores ut est qui facilis qui ratione. Voluptatem sunt delectus eaque non cupiditate exercitationem. Enim est aut itaque quasi. Quo officiis sint consequuntur vel itaque quaerat. Quaerat occaecati quia velit accusamus cum totam exercitationem. Vitae natus et aliquam doloribus esse et. Quia voluptatem voluptatibus quia dolorem aperiam culpa voluptatem. Voluptas at ut veritatis soluta. Optio nam velit ad labore. Tenetur tempora dicta incidunt. Consequatur amet ut dolorem sit enim est aperiam quia. Inventore eaque nesciunt repellendus neque aut ea quos. Dolor quis et voluptas.', '2023-01-22', '2023-01-22', '650.00', 'KES', '(475) 877-6156', 'bbarton@wolf.net', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(76, 'Alva Ondricka', 'aspernatur-et-quam-soluta-error-dolor-ut', 'Velit quis est natus hic quia enim. Ad laboriosam nostrum reprehenderit rerum fugit. Ea quae perferendis unde voluptas et voluptatem. Veritatis dicta qui a nostrum quo nesciunt dolorem. Voluptas amet sit repellat temporibus eos maxime repellendus. Laudantium maiores non sit aliquam ut occaecati nihil. Debitis commodi est consequatur quibusdam ut temporibus facilis commodi. Sed et sapiente repellat eos sit natus quae sint. Rerum dolore odio consequatur repellat quo quas. Id iure quo rerum quia dolorum.', '2023-03-22', '2023-03-22', '3374.00', 'KES', '(380) 453-4620', 'wiza.reed@hotmail.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(77, 'Maddison West', 'quae-est-modi-ipsum-ab-id-quos-reprehenderit', 'Dolorum commodi quisquam rem ipsum voluptate velit. Fuga molestiae eos rerum alias repudiandae. Facere debitis laudantium corporis. Deserunt ut mollitia blanditiis magni a maxime. Explicabo ab ut deleniti dolorum aspernatur. Veniam repellendus amet dolor. Delectus magnam ullam eum minima. Facilis consectetur vitae molestiae cum. Voluptatem culpa vitae nulla. Voluptas fuga non aut optio sint voluptatem. Harum harum at sapiente laboriosam aliquam maxime. Aut eveniet fugit explicabo iure delectus.', '2023-06-22', '2023-06-22', '3171.00', 'KES', '+13858590489', 'margarett.wisoky@hotmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(78, 'Jose Kuphal IV', 'placeat-molestias-possimus-corrupti', 'Officia repellendus saepe dolores harum ipsa. Sequi dolorem inventore a nesciunt magni officia accusamus. Eveniet dignissimos quaerat laboriosam itaque qui optio. Cum quia rerum animi fuga molestiae. Doloribus voluptatem ex necessitatibus qui. Id aliquid dignissimos architecto possimus sint. Molestiae sit ratione tempore sed quis ut. Occaecati quo dolore ipsam. Ab aperiam molestiae et quo accusamus deleniti.', '2023-01-22', '2023-01-22', '1927.00', 'KES', '+17549067433', 'gherzog@yahoo.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(79, 'Alexander Tremblay IV', 'magni-eveniet-ratione-qui-necessitatibus-laborum-veritatis', 'Rerum ut veritatis ut. Necessitatibus numquam id explicabo voluptatibus aspernatur omnis. Quo quam recusandae commodi voluptatem. Aut eius aut dolor fugit voluptas consequuntur. Iusto est qui maiores quibusdam. Itaque sit est nisi libero ea. Quidem nesciunt atque quibusdam placeat et voluptatem consequatur error. Ut assumenda temporibus magni quia magnam quas voluptatem consequuntur. Consequuntur accusamus at neque sunt voluptas et perspiciatis.', '2023-02-22', '2023-02-22', '1934.00', 'KES', '+1-520-819-4455', 'roob.beatrice@emard.biz', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(80, 'Dante Kunde', 'quam-perspiciatis-magnam-veritatis-ut-dolores', 'Rerum architecto minus voluptatem esse. Odit qui ut sapiente nemo deserunt quasi eius. Dolor exercitationem ut eligendi qui. Corrupti optio in deserunt molestiae dicta. Tenetur autem repudiandae pariatur eum. Non et facilis modi quos nihil quae ipsum est. Ipsam ipsa blanditiis eius totam commodi. Accusamus sed hic qui asperiores modi. Aut sed voluptas voluptatem sequi aspernatur. Dolorem deleniti laudantium doloremque unde assumenda eos dolores. Asperiores voluptas voluptas facilis quidem. Eum nisi quam quisquam excepturi et dolor.', '2023-05-22', '2023-05-22', '4604.00', 'KES', '1-321-740-6382', 'kennedy31@gmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(81, 'Janie Welch', 'nisi-rerum-distinctio-aspernatur-voluptatem-optio', 'Ut repellat repudiandae accusantium reprehenderit dolore. Ut temporibus ut magni ipsa perspiciatis. Odit a placeat qui non quis natus. Qui possimus dolorem blanditiis alias. Ut est quod ut excepturi corrupti minima. Eius magni facere recusandae voluptates qui. Natus porro qui deserunt est molestias illum. Mollitia est sed dolorem vel iusto. Corporis neque sapiente saepe molestiae debitis et ad. Sit autem ex est vel. Voluptas est voluptatem expedita nam quo nemo. Dolorum qui nulla velit laboriosam numquam cupiditate in adipisci. Omnis maiores cumque iste consequuntur consequatur vitae pariatur. Facilis dolorum doloremque eveniet voluptatem officiis.', '2023-08-22', '2023-08-22', '5240.00', 'KES', '+1.704.424.1295', 'kozey.beulah@barton.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(82, 'Alexandria Runolfsson DDS', 'voluptates-delectus-doloremque-totam-debitis-eligendi-earum', 'Officia dolores non suscipit debitis est quidem et. Dicta ut optio sit dolorem ratione voluptate ut natus. Enim ut quisquam est quia ullam qui eaque. Dolorem tenetur incidunt dignissimos totam qui repellendus. Quo qui inventore quia recusandae fugit laboriosam voluptates. Est quos voluptatem nihil cupiditate occaecati sunt veritatis. In et omnis cupiditate officiis impedit autem in.', '2023-09-22', '2023-09-22', '5732.00', 'KES', '+1-551-942-0781', 'nash36@gaylord.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(83, 'Candido Ondricka', 'possimus-ipsam-aut-omnis-sit-incidunt-rerum-vero', 'Ducimus magni et ea hic rerum et. Optio et quod impedit facilis qui beatae. Sed odit natus dolor. Unde velit itaque excepturi molestiae saepe enim. Fugit laborum aliquid non consequatur similique molestiae. Maiores quae soluta eius illo nihil ipsa. Rem earum nihil voluptatem molestiae. Officiis velit quisquam ea ducimus molestiae iure temporibus porro.', '2023-05-22', '2023-05-22', '4503.00', 'KES', '+14133807996', 'nleannon@kshlerin.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(84, 'John Frami', 'sed-debitis-dignissimos-quis-ab-voluptate-quaerat', 'Blanditiis doloribus corporis quod vitae. Totam ipsum reiciendis suscipit aut. Earum totam dolor qui et quo rerum vitae et. Adipisci cumque quia cupiditate praesentium sed delectus. Iusto veritatis atque tempore cupiditate saepe ea. Facere quis voluptatem ullam sed sapiente. Ratione consequatur sit dolores.', '2023-04-22', '2023-04-22', '5598.00', 'KES', '+1 (831) 368-0770', 'kasey.muller@mante.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(85, 'Willow Schimmel', 'quo-dolor-et-esse-dicta-quisquam', 'Inventore et harum doloremque et omnis magni deleniti. Impedit corrupti ex rem dolores repudiandae sed voluptates voluptas. Rerum ratione vitae quos ex atque laudantium. Atque reiciendis exercitationem illum delectus quas et. Pariatur et aut architecto a. Nobis eum et vel aut saepe. Aliquid dolor similique eveniet ipsam voluptatem veritatis hic repudiandae. Vitae porro iusto voluptates molestias aut. Aut laborum in sunt cumque modi eum recusandae.', '2023-09-22', '2023-09-22', '4061.00', 'KES', '661.487.4844', 'maegan.swift@hotmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(86, 'Destiney Konopelski Jr.', 'est-omnis-id-voluptatem-ratione-assumenda-dolorem-reiciendis', 'Sed ab consequatur sapiente. Nihil eaque earum et eos aperiam nam. Inventore quia incidunt rerum. Ea nihil in iusto a cupiditate sunt et. Possimus id accusamus necessitatibus et sequi eligendi. Ut qui vitae provident dolore nulla dolores qui distinctio. Atque quo sit ipsam quaerat tempora deserunt qui. Laborum vitae eos qui praesentium maiores quidem. Ut porro animi voluptatem quo eum. Dicta nemo odit est tempora.', '2023-03-22', '2023-03-22', '1284.00', 'KES', '(216) 225-6109', 'kpredovic@gmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(87, 'Ed West', 'et-nihil-et-explicabo-aut-rerum-est-facere', 'Autem alias ut fugit. Quia et occaecati rem aperiam. Voluptas doloremque ut incidunt veniam cupiditate blanditiis suscipit. Et accusantium minus omnis tempora et incidunt. Voluptas doloremque aut vitae praesentium consequatur. Et vitae ea a optio est molestias omnis et. Nihil ipsam dicta molestias placeat earum qui debitis. Expedita consequuntur est labore voluptatum qui dignissimos.', '2023-02-22', '2023-02-22', '2227.00', 'KES', '(726) 391-5991', 'mylene.abshire@gmail.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(88, 'Jettie Gleichner', 'veniam-doloribus-pariatur-praesentium-minima-cumque-ex-voluptas-mollitia', 'Quidem facilis sint autem. Nisi voluptatem numquam omnis cupiditate ut et. Quibusdam quis qui non ex tempora reprehenderit. Molestiae qui quia velit sint itaque voluptatibus. Illo nam voluptatem accusamus ipsam dolorem beatae. Asperiores iste dolor sunt corrupti fugiat voluptatum. Minus tempora fugiat et fugit autem magnam sunt. Saepe recusandae necessitatibus omnis eveniet et. Eligendi vero rerum nam. Nostrum saepe dolores unde dolore. Omnis at perspiciatis sint voluptate laudantium atque autem.', '2023-06-22', '2023-06-22', '4982.00', 'KES', '1-678-310-7610', 'maia06@quitzon.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(89, 'Prof. Dariana Parker III', 'qui-soluta-odio-repellat-mollitia-libero-ut-assumenda', 'Deserunt dolores vel id repudiandae perferendis saepe. Consequatur libero non nisi dignissimos. Beatae eos et voluptas. Qui esse quidem maiores consectetur sint. Eveniet id cumque fugit quibusdam quam sit. Maxime fugit illum qui voluptatem. Eos veniam magnam accusamus adipisci eaque ut eius. Fugit qui et eveniet voluptas sunt. Qui ab exercitationem quia. Distinctio eum dicta nihil veniam. Aperiam enim quia magni consequatur.', '2023-05-22', '2023-05-22', '2657.00', 'KES', '1-575-664-8225', 'hazel.hintz@yahoo.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(90, 'Sebastian Rau', 'fugit-natus-sequi-vitae-eveniet-et-placeat', 'Placeat odit cupiditate perspiciatis iste. Consequatur saepe voluptatem deleniti consequatur fugit asperiores. Accusamus iure quisquam ratione officia numquam. Voluptas sint sunt ex aut cum quos. Iste enim distinctio eum molestiae. Voluptatum placeat tenetur nihil saepe sint aut. Aperiam et voluptatem veniam quo deleniti vel omnis. Consequatur impedit qui iure quidem molestiae dicta ratione id. Repudiandae ducimus deserunt iusto non ipsam harum et. Exercitationem dolores inventore sequi sit. Animi voluptatibus itaque similique eius tempora quaerat.', '2023-02-22', '2023-02-22', '3009.00', 'KES', '1-351-751-7932', 'wuckert.lucy@yahoo.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(91, 'Caroline Shanahan', 'numquam-animi-reiciendis-fugit-quia-occaecati', 'Deserunt quia totam impedit dolores ad. Ut nesciunt voluptatum et voluptas pariatur. Non modi a magnam suscipit. Sequi inventore tenetur quisquam. Quibusdam explicabo perferendis sed ullam ullam. Velit est et tenetur praesentium mollitia impedit. Magnam ut culpa ipsa veniam quos. Temporibus alias veritatis sed enim autem. Dolorem id consequatur earum impedit. Velit sint assumenda necessitatibus quo. Et laboriosam eum eos provident. Impedit nihil culpa iste sit eos. Pariatur repellat aliquam quidem quibusdam officia maxime.', '2023-04-22', '2023-04-22', '1065.00', 'KES', '248.306.3714', 'kennedi85@abbott.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(92, 'Katharina Roob IV', 'aut-occaecati-molestias-molestiae-autem', 'Rerum voluptas fuga aliquid dolor. Et numquam est provident quidem. Molestiae doloremque quis tempora necessitatibus. Deleniti iusto sapiente animi et deleniti quis. Ea est aut quo mollitia fuga odio. Accusantium non odio incidunt est. Optio dignissimos libero earum facere illo et amet rerum. Autem autem ab sed accusantium dolorem quo officia vel. Alias rerum cum ea placeat ut et. Cum voluptatem saepe libero dolor sequi optio tempore. Placeat itaque quod officia veniam.', '2023-05-22', '2023-05-22', '2496.00', 'KES', '(732) 952-2998', 'cole.bobbie@yahoo.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(93, 'Candelario Lang Sr.', 'omnis-ratione-consequatur-beatae-iure-cumque-id-deleniti-enim', 'Laborum ullam vel porro. Eius consequatur ut amet qui laborum velit maxime culpa. Aspernatur et ratione illo praesentium et. In cum enim libero eum ipsum non fuga voluptatem. Voluptas vero est quidem quia culpa. Repellat veniam ad illo nihil. Porro et quibusdam sint. Unde quia eos vero ut veritatis. Et id debitis voluptas autem. Commodi et temporibus unde aliquid. Similique quia fugit autem distinctio qui dolor. Fugit non blanditiis tenetur minima quae vitae aspernatur. Explicabo eius similique ex nostrum quas dolores consectetur.', '2023-04-22', '2023-04-22', '4878.00', 'KES', '+1-614-657-3017', 'marielle.bechtelar@lakin.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(94, 'Miss Stella Swift', 'ea-fuga-eos-eius-aut-omnis', 'Voluptatem debitis porro veritatis sint qui qui hic. Rem quasi eligendi error est commodi temporibus assumenda. Ut ea at sapiente sed eos quis eum. In necessitatibus nisi sit dolorem aut. Officiis qui deleniti iure eveniet praesentium id sint et. Sunt qui similique voluptates voluptas ullam. Quidem quia doloribus praesentium ab iste exercitationem amet. Aut in labore non nemo aliquid ea facere. Ut natus aut voluptas deleniti. Quidem quas porro voluptatibus qui at.', '2023-03-22', '2023-03-22', '3261.00', 'KES', '610.814.6974', 'cassin.yasmin@muller.biz', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(95, 'Mr. Oda Zulauf', 'veritatis-dicta-odit-qui-dolorem-omnis', 'Rerum at pariatur odit quibusdam aliquid quaerat. Libero blanditiis molestiae inventore ex. Temporibus eius impedit ut molestias non quis saepe. Ut omnis exercitationem necessitatibus debitis. Non minima est omnis ut earum dolor inventore. Ipsum nemo voluptatem illum sed cumque voluptatem ipsa dolores. Ut dolores aut dolorem molestiae nobis voluptatem. Aliquam asperiores architecto fugiat est hic veritatis.', '2023-02-22', '2023-02-22', '743.00', 'KES', '(610) 918-9415', 'sophie.batz@gmail.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(96, 'Mariane Johns', 'sit-in-dolorem-eos-et-quia-voluptas-vel', 'Quisquam et omnis similique tempora qui expedita sunt. Est placeat repellat consequatur. Aliquid ut nulla necessitatibus ipsam reprehenderit. Praesentium voluptatum non pariatur quae. Et voluptatem sed voluptas reiciendis a. Voluptatem quisquam et et pariatur numquam aut quis nisi. Quia consequatur ab et tenetur tenetur sed sint. Voluptas dolores qui voluptatem iusto magnam quia dolores. Enim aperiam est et natus consequatur aut. Incidunt dolores officia distinctio autem necessitatibus quaerat rem laborum. Repellat vel sapiente perferendis minima earum maiores. Quia totam vitae vero tenetur amet nostrum aspernatur. Sapiente est quis et.', '2023-03-22', '2023-03-22', '2305.00', 'KES', '740-967-1240', 'logan14@gmail.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(97, 'Madilyn Weissnat', 'dolorem-soluta-quis-ut-illum-neque-est', 'Commodi accusamus vero nihil autem in. Laborum ex ut minima. Ad molestiae impedit recusandae dignissimos dolore ut in. Veritatis nihil voluptatem sed sint ut occaecati. Sed assumenda voluptas voluptas pariatur accusantium cupiditate possimus. Sit libero exercitationem atque. Cum mollitia totam enim quod numquam vitae. Sint eveniet reiciendis eligendi libero optio amet in qui. Eveniet voluptas ut maxime corporis corrupti.', '2023-01-22', '2023-01-22', '3592.00', 'KES', '740-672-6542', 'fisher.edwina@gmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(98, 'Dr. Louisa Franecki', 'esse-ea-maxime-culpa-dolorem-earum', 'Odio voluptate sint suscipit aliquid dolores est. Ipsum fugit aspernatur et nemo quos quia voluptatem. Deleniti accusantium molestiae minima ut vero nesciunt quidem. Id sit aut omnis iure tempora. Alias magnam nesciunt quia quia cum in. Illum voluptatem et autem quos porro ad. Ab dolores et maxime. Accusantium atque cum voluptatem sint. Quibusdam incidunt perferendis nam molestias quia.', '2023-02-22', '2023-02-22', '7556.00', 'KES', '+1-413-647-8585', 'raymundo16@gibson.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(99, 'Cooper Kling', 'nulla-sequi-quo-voluptatem-dolor-tempore-quidem-sunt', 'Quis inventore sed sunt nulla quia est ipsa. Velit ut exercitationem alias aut eos. Doloremque autem consequatur velit dolorem. Rem nihil quis animi neque. Ut et vel deleniti est esse voluptas fugiat vel. Laudantium in ut nostrum expedita quia dolor est. Dolorem aut laudantium fugiat rerum. Laboriosam provident quae eligendi unde voluptatem. Omnis ipsam soluta incidunt possimus. Sapiente id ad animi possimus doloremque. Ducimus omnis nisi quo. Qui quas et et alias.', '2023-02-22', '2023-02-22', '6842.00', 'KES', '870.425.4489', 'rogahn.judd@mohr.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(100, 'Christine Runte', 'animi-praesentium-voluptatibus-iusto-odio-illum', 'Quae modi eos omnis at. Distinctio rerum incidunt aspernatur et. Possimus totam temporibus aut dolor in nobis. Rerum eum eum tempora facilis quo labore ut. Voluptatem nobis veritatis aut eum eum esse. Iure ut incidunt impedit. Ipsum ducimus numquam non eaque. Molestiae architecto inventore qui deserunt quisquam maiores. Iusto qui beatae consectetur vero. Dolores cupiditate enim accusamus doloribus. Nulla sunt neque totam vel qui deserunt ducimus. Temporibus voluptatum est delectus temporibus cum ut voluptatibus. Ut suscipit ex rerum doloremque voluptate. Cumque modi numquam aut voluptatum.', '2023-03-22', '2023-03-22', '516.00', 'KES', '+1 (681) 352-3021', 'ben.lubowitz@gmail.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:29:37', '2022-11-22 04:29:37'),
(101, 'Naomi Schroeder Sr.', 'eum-voluptates-a-non-voluptates-ipsa', 'Aut delectus neque optio sit. Eos laudantium qui enim aperiam minus tempore facere. Beatae consequatur sit qui non asperiores. Molestiae consequuntur repellendus odio suscipit qui omnis aut quaerat. Molestias in est incidunt dolorem eveniet ratione. Quos tempora et consequatur dolor velit. Laboriosam illo sint aspernatur incidunt quia et ut aut. Quis est repellendus numquam deserunt repudiandae ipsa maxime. Odio velit voluptatem eius occaecati qui. Quia aliquam enim ducimus. Est sint asperiores et eos eligendi in ex odit. Delectus aut repellat est perspiciatis.', '2023-01-22', '2023-01-22', '4241.00', 'KES', '(831) 969-0149', 'jadyn.kovacek@yahoo.com', 4, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:37:35', '2022-11-22 04:37:35'),
(102, 'Rubye Wyman DDS', 'qui-atque-qui-deserunt-sit-aut', 'Sed aut accusantium quibusdam dolorem enim perspiciatis excepturi qui. Blanditiis minus consequatur maiores quia est eveniet quisquam et. Est reiciendis quia assumenda doloribus ipsum dolorem soluta. Nemo rerum omnis enim enim eos non et est. Molestias eos sint officia. Distinctio optio quis quae asperiores sed repellendus quis. Est et mollitia nostrum voluptates eligendi magnam. Amet explicabo fuga a ut porro. Dolore neque molestiae quam fugit pariatur. Quisquam sunt quaerat quo.', '2023-05-22', '2023-05-22', '2826.00', 'KES', '+1-386-539-2095', 'simeon.hills@gmail.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:37:58', '2022-11-22 04:37:58'),
(103, 'Amanda Mante', 'dolorem-a-ipsa-fugiat-temporibus-qui-sint-facilis', 'Saepe et voluptatem consequatur voluptatem. Accusamus et et nisi quam mollitia odio. Occaecati quod quia iure unde. Consequatur amet dolorem quia sed cumque. Eum ea libero sunt ab quos consequatur fuga accusantium. Ut quam illum vitae ipsa molestias animi laboriosam qui. Modi officia assumenda nemo vel magnam assumenda explicabo deleniti. Et corrupti nobis perferendis illum minima est. Sed iure eligendi rem minima. Eum vel ex quos molestias voluptatem iusto quis. Amet quasi voluptatum odit eius quo modi. Quo omnis accusamus et nobis aut sed.', '2023-02-22', '2023-02-22', '5977.00', 'KES', '+1-561-744-6274', 'tony.spinka@yahoo.com', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:38:27', '2022-11-22 04:38:27'),
(104, 'Jovan Shanahan', 'sequi-a-natus-aut-nobis-repellendus-labore', 'Iusto animi dolore consequatur eos. Id rerum ut ratione eum vel est illo dolorem. Dolor nisi et alias sunt ad sit in. Aliquam ut adipisci consequatur aut sunt exercitationem. Soluta asperiores et sit optio temporibus soluta distinctio culpa. Optio et et nemo doloribus. Ipsum et qui est. Eius quisquam architecto ab aperiam occaecati architecto sunt nulla. Et quia et dicta asperiores quisquam soluta impedit. Ut et delectus tempore corrupti quo nihil blanditiis vitae. Dolorem optio quidem dolorem rem.', '2023-04-22', '2023-04-22', '5808.00', 'KES', '1-334-580-9832', 'mjacobi@gmail.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:38:32', '2022-11-22 04:38:32'),
(105, 'Dean Koelpin', 'quo-quia-eum-suscipit-nemo-laboriosam-quo-eos', 'Velit qui cupiditate qui id explicabo. Sit unde enim dolorem omnis architecto qui non. Voluptates excepturi placeat in inventore nulla repellat blanditiis. Et temporibus placeat labore dolore earum. Quos dolor et et sit et ea. Molestiae maxime maxime odit aut esse. Molestiae et provident esse maiores voluptates id. Et laborum vitae dolore facilis. Aliquam voluptatibus placeat rerum sunt voluptas qui provident.', '2023-08-22', '2023-08-22', '6628.00', 'KES', '+14016043750', 'oconner.estel@dietrich.com', 1, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:44:30', '2022-11-22 04:44:30'),
(106, 'Edwina Gerhold', 'cumque-aut-incidunt-eum', 'Ab velit quia perspiciatis itaque laudantium ipsam ducimus. Doloremque cumque voluptatibus et ut. Et esse minima consequatur minus qui. Rerum voluptas ut omnis perferendis provident quasi earum sed. Ad accusantium dolorem aliquam nulla. Consequatur illo unde et temporibus. Ea nostrum expedita enim dolor possimus nulla dicta officiis. Quia qui esse quia et odio sunt. Accusamus rerum molestias ex et est. Velit eum qui doloremque totam consequuntur enim. Aut magni asperiores ea odio eos. Vero quis corporis dolores ipsam. Provident fugit in laudantium.', '2023-05-22', '2023-05-22', '5542.00', 'KES', '(423) 839-0496', 'jessika19@auer.net', 3, 'car.jpg', 1, 1, 1, 1, '2022-11-22 04:44:32', '2022-11-22 04:44:32'),
(107, 'Sunt molestias sed m', 'sunt-molestias-sed-m', 'Est placeat et expe', '2022-11-26', '2022-11-16', '763.00', 'KES', '+1 (584) 757-1615', 'bylihicoh@mailinator.com', 1, 'LpkndpxvR91LP2lnsr0rlrMlyrEojm.png', 1, 1, 1, 1, '2022-11-22 05:20:29', '2022-11-22 05:20:29'),
(108, 'Mr.', 'mr-', 'Recusandae voluptatem ut praesentium vero. Cum est porro et. Exercitationem sapiente modi voluptatem adipisci exercitationem nisi. Non omnis quod rerum officiis voluptatem. Voluptas nam corporis eius amet ea nesciunt. Voluptatem sint laborum est voluptatibus. Sit iusto officiis consequuntur accusantium ex sint velit. Non consequatur maiores sequi sint explicabo totam aut voluptas. Qui recusandae est aut culpa debitis incidunt. Consectetur aut earum veniam. Aut praesentium blanditiis doloribus fuga. Porro enim est occaecati esse. Non odio reiciendis qui sed. Mollitia repellat facere omnis similique voluptatem accusamus dolor.', '2022-11-22', '2022-11-22', '6252.00', 'KES', '+1.469.776.9183', 'reyes.connelly@hotmail.com', 3, NULL, 1, 1, 8, 8, '2022-11-22 05:29:57', '2022-11-22 05:29:57'),
(109, 'Dr.', 'dr-', 'Itaque enim voluptatibus dolores minima. Incidunt vero repellendus autem et. Excepturi quo dolor dolor nobis quia debitis. Repellendus debitis dicta et voluptas. Laborum ea vero quia id velit. Quisquam quae voluptas sit animi autem ut esse eos. Occaecati veniam ut ab qui aut. Et quasi explicabo in. Perspiciatis est atque sit quaerat natus. Repellendus voluptas et ipsa aut voluptas. Quia labore corrupti placeat consequatur delectus veritatis saepe. Beatae aliquid maxime fugit et. Minima minima praesentium praesentium et et sapiente. Doloribus omnis est iusto officia sit.', '2022-11-22', '2022-11-22', '5847.00', 'KES', '1-484-321-1260', 'constance.kuphal@gmail.com', 3, 'wBIw24lllC8xWkGZadS2qFKI7VOjRF.jpg', 1, 1, 9, 9, '2022-11-22 05:30:19', '2022-11-22 05:30:19'),
(110, 'Ms.', 'ms-', 'Asperiores voluptatem qui porro veniam similique vel impedit. Tempore commodi quasi a animi nostrum qui alias. Vel laudantium qui non at suscipit ipsa sed. Assumenda exercitationem earum nobis illo earum. Qui magni architecto quasi dignissimos omnis. Dolor voluptates delectus ipsam. Architecto facilis enim in cupiditate quod.', '2022-11-22', '2022-11-22', '2380.00', 'KES', '+1-614-484-5550', 'ihyatt@yahoo.com', 3, 'OqPZib6lP1iXDerJ8ZkUOEfVCRrcM5.jpg', 1, 1, 11, 11, '2022-11-22 05:36:35', '2022-11-22 05:36:35'),
(111, 'Mrs. Rosina Christiansen MD', 'mrs-rosina-christiansen-md', 'Quod voluptatibus occaecati molestias atque consequatur est corporis. Totam laborum doloremque magnam earum sed facilis et cum. Dolores repudiandae vel est labore veritatis ad non. Quae molestias cupiditate ex aliquid molestiae. Commodi veritatis officiis voluptas sit voluptatum illo sit. Quo quas ex voluptas quos. Et sed et fugit ut. Natus sit ut animi architecto quia eos. Recusandae fuga inventore dolor est qui nam quaerat.', '2022-11-22', '2022-11-22', '5912.00', 'KES', '(619) 849-3141', 'zoconner@hane.com', 3, '9uUyLMeqXCbQVLObSPDaWy92DHZir8.jpg', 1, 1, 12, 12, '2022-11-22 05:39:00', '2022-11-22 05:39:00'),
(112, 'Eum Nam omnis qui co', 'eum-nam-omnis-qui-co', 'Non eu asperiores co', '2022-12-01', '2022-11-17', '261.00', 'KES', '+1 (137) 817-2752', 'podef@mailinator.com', 4, 'FsZIgujZeESeSXynQmgYik1I9kX8X4.jpg', 1, 1, 1, 1, '2022-11-22 06:01:09', '2022-11-22 06:01:09'),
(113, 'Lyla Emard', 'ullam-incidunt-inventore-ipsa-consequuntur', 'Consequatur qui saepe consequatur quis aut vero recusandae beatae. Quidem eveniet quo facilis aliquam rerum at qui. Facilis tempora officia cupiditate id in nostrum. Aut et ullam reiciendis possimus est facere dicta voluptate. Qui dolorem saepe eos et. Veritatis autem aut delectus rerum iure facere. Nostrum assumenda ab delectus ut. Dolores suscipit officia consequatur earum.', '2023-09-22', '2023-09-22', '745.00', 'KES', '+1.360.593.8832', 'jennifer04@monahan.com', 2, 'car.jpg', 1, 1, 1, 1, '2022-11-22 06:08:35', '2022-11-22 06:08:35');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provider_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `avatar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `provider_id`, `avatar`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'Kevin Ochieng', 'kvnochieng52@gmail.com', '107001482402476521296', 'https://lh3.googleusercontent.com/a/ALm5wu2M8oqaaYhv8CFxc1_3H5_uFnRRf1J3vwcH4HgNbg=s96-c', NULL, NULL, NULL, '2022-11-22 04:30:10', '2022-11-22 04:30:10'),
(2, 'Dr. Kasandra Hill I', 'agustin.stoltenberg@example.net', NULL, NULL, '2022-11-22 04:32:14', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'BXxe5srU86', '2022-11-22 04:32:14', '2022-11-22 04:32:14'),
(3, 'Mr. Maynard Gusikowski PhD', 'kihn.guy@example.com', NULL, NULL, '2022-11-22 05:21:20', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'f4xBcaVHxB', '2022-11-22 05:21:20', '2022-11-22 05:21:20'),
(4, 'Shanel Donnelly', 'beier.josiane@example.com', NULL, NULL, '2022-11-22 05:22:31', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'q38JHSEddl', '2022-11-22 05:22:31', '2022-11-22 05:22:31'),
(5, 'Christophe Morissette DVM', 'oschaefer@example.org', NULL, NULL, '2022-11-22 05:25:26', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'ZbKJshNWDC', '2022-11-22 05:25:26', '2022-11-22 05:25:26'),
(6, 'Cassidy Mayert', 'damon.kutch@example.org', NULL, NULL, '2022-11-22 05:27:00', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Pd3BiM4clS7lVgSypuDF16zoT4D3N1qMY1zow2qle5cBfG5EXDouJu9kBbfy', '2022-11-22 05:27:00', '2022-11-22 05:27:00'),
(7, 'Maurice Stoltenberg', 'brock.beier@example.com', NULL, NULL, '2022-11-22 05:28:17', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'w2k1lgC1nk', '2022-11-22 05:28:17', '2022-11-22 05:28:17'),
(8, 'Howard Halvorson Sr.', 'augustus.rutherford@example.org', NULL, NULL, '2022-11-22 05:29:54', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '4LzeMwNlWWqfc8vCpiq99eDCVwBHON3k4JXjKtU5IJ5L9mX1jAKXcq8rKQ2t', '2022-11-22 05:29:54', '2022-11-22 05:29:54'),
(9, 'Mr. Emil Bins Jr.', 'keebler.dakota@example.com', NULL, NULL, '2022-11-22 05:30:16', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'KaO2nw49ZzHVyaht3Tu2pwg1mTQKgWk6zTQDf9Pad0FrTm5lBgVc150FoyJZ', '2022-11-22 05:30:16', '2022-11-22 05:30:16'),
(10, 'Leann Parker Sr.', 'iritchie@example.net', NULL, NULL, '2022-11-22 05:33:16', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'zrJoThph3F', '2022-11-22 05:33:16', '2022-11-22 05:33:16'),
(11, 'Kolby Lynch', 'mellie86@example.com', NULL, NULL, '2022-11-22 05:36:32', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'm6ACAyekrHvwBFodwLRttHBPYuJ8wwCIiSId3WCmtFUeCCcJA3YMofdbF4Dk', '2022-11-22 05:36:32', '2022-11-22 05:36:32'),
(12, 'Samara Lesch', 'ccasper@example.com', NULL, NULL, '2022-11-22 05:38:57', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'VhgPzb0ncu0mWwYMwTMn12h6QbPSRXPgEYEQo1UMCaF8qZAiA02o0GoOuvtA', '2022-11-22 05:38:57', '2022-11-22 05:38:57');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=114;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
